import argparse
import os
import sys
import json
from datetime import datetime

class RosettaCLI:
    def __init__(self):
        self.parser = argparse.ArgumentParser(description="Repo Rosetta - Codebase Understanding Tool")
        self._setup_args()

    def _setup_args(self):
        self.parser.add_argument("path", help="Path to the repository to analyze", default=".")
        self.parser.add_argument("--verbosity", choices=["scan", "brief", "standard", "deep"], default="standard")
        self.parser.add_argument("--persona", choices=["beginner", "intermediate", "senior-engineer", "architect", "pm"], default="senior-engineer")
        self.parser.add_argument("--llm", help="LLM provider to use (e.g., ollama, anthropic, gemini)")
        self.parser.add_argument("--output", help="Output directory", default="./docs/rosetta")
        self.parser.add_argument("--format", choices=["markdown", "json"], default="markdown")

    def run(self):
        args = self.parser.parse_args()
        print(f"[*] Analyzing codebase at: {os.path.abspath(args.path)}")
        print(f"[*] Configuration: Verbosity={args.verbosity}, Persona={args.persona}")
        
        if not os.path.exists(args.path):
            print(f"[!] Error: Path {args.path} does not exist.")
            sys.exit(1)

        # Mock analysis flow
        print("[*] Parsing files...")
        print("[*] Generating knowledge graph...")
        print("[*] Generating summaries (using {} LLM)...".format(args.llm or "default"))
        
        self._generate_output(args)

    def _generate_output(self, args):
        if not os.path.exists(args.output):
            os.makedirs(args.output)
            
        if args.format == "markdown":
            self._write_codebase_md(args)
        else:
            self._write_json_export(args)

    def _write_codebase_md(self, args):
        content = f"""# CODEBASE.md - {os.path.basename(os.path.abspath(args.path))}

## Overview
This is a generated architecture guide for the repository.

## Configuration
- **Generated on**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Persona**: {args.persona}
- **Verbosity**: {args.verbosity}

## Architecture Map
```mermaid
graph TD
    A[Root] --> B[Source]
    B --> C[Library]
```

## Module Reference
| Module | Description |
|---|---|
| src/ | Core logic |
| docs/ | Documentation |

Generated by Repo Rosetta.
"""
        filename = f"codebase_{args.persona.replace('-', '_')}_{args.verbosity}.md"
        filepath = os.path.join(args.output, filename)
        with open(filepath, "w") as f:
            f.write(content)
        print(f"[+] Analysis complete. Results saved to: {filepath}")

    def _write_json_export(self, args):
        data = {
            "version": "1.0.0",
            "timestamp": datetime.now().isoformat(),
            "config": {
                "persona": args.persona,
                "verbosity": args.verbosity
            },
            "nodes": [],
            "edges": []
        }
        filename = f"codebase_{args.persona.replace('-', '_')}_{args.verbosity}.json"
        filepath = os.path.join(args.output, filename)
        with open(filepath, "w") as f:
            json.dump(data, f, indent=2)
        print(f"[+] Analysis complete. Results saved to: {filepath}")

if __name__ == "__main__":
    cli = RosettaCLI()
    cli.run()
